# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(False)
        MainWindow.resize(552, 472)
        MainWindow.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: rgba(255, 255, 255,0);\n"
"    \n"
"}\n"
"QPushButton {\n"
"    \n"
"    font: 12pt;\n"
"    border: 3px solid #DAA520;\n"
"    border-radius: 11px;\n"
"}\n"
"\n"
"QLabel {\n"
"    \n"
"    color: #000000;\n"
"    border: 5px solid #DAA520;\n"
"    border-top-right-radius:70px;\n"
"    border-top-left-radius:70px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 551, 471))
        self.frame_2.setStyleSheet("background-color: rgb(89, 150, 177);\n"
"border-top-right-radius:70px;\n"
"border-top-left-radius:70px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 210, 120, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(280, 270, 120, 50))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_9.setGeometry(QtCore.QRect(280, 330, 120, 50))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 20, 510, 120))
        font = QtGui.QFont()
        font.setPointSize(38)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 330, 120, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 210, 120, 50))
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_10.setGeometry(QtCore.QRect(410, 150, 120, 50))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 270, 120, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_15.setGeometry(QtCore.QRect(280, 390, 250, 50))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 390, 120, 50))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_19.setGeometry(QtCore.QRect(150, 150, 120, 50))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_17.setGeometry(QtCore.QRect(410, 210, 120, 50))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(150, 270, 120, 50))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 210, 120, 50))
        self.pushButton.setStyleSheet("QPushButton { Size: 20px 20px; }\n"
"\n"
"QPushButton:hover { \n"
" \n"
"background-color: rgb(89, 150, 177);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_8.setGeometry(QtCore.QRect(150, 330, 120, 50))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_16.setGeometry(QtCore.QRect(20, 150, 120, 50))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_11.setGeometry(QtCore.QRect(410, 270, 120, 50))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_18.setGeometry(QtCore.QRect(280, 150, 120, 50))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_12.setGeometry(QtCore.QRect(410, 330, 120, 50))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_13.setGeometry(QtCore.QRect(150, 390, 120, 50))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_18.raise_()
        self.pushButton_5.raise_()
        self.pushButton_14.raise_()
        self.pushButton.raise_()
        self.pushButton_19.raise_()
        self.pushButton_8.raise_()
        self.pushButton_11.raise_()
        self.pushButton_17.raise_()
        self.pushButton_2.raise_()
        self.pushButton_4.raise_()
        self.pushButton_10.raise_()
        self.pushButton_12.raise_()
        self.label.raise_()
        self.pushButton_3.raise_()
        self.pushButton_13.raise_()
        self.pushButton_7.raise_()
        self.pushButton_6.raise_()
        self.pushButton_9.raise_()
        self.pushButton_15.raise_()
        self.pushButton_16.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "8"))
        self.pushButton_7.setText(_translate("MainWindow", "6"))
        self.pushButton_9.setText(_translate("MainWindow", "3"))
        self.pushButton_3.setText(_translate("MainWindow", "1"))
        self.pushButton_5.setText(_translate("MainWindow", "9"))
        self.pushButton_10.setText(_translate("MainWindow", "X"))
        self.pushButton_2.setText(_translate("MainWindow", "4"))
        self.pushButton_15.setText(_translate("MainWindow", "="))
        self.pushButton_14.setText(_translate("MainWindow", "."))
        self.pushButton_19.setText(_translate("MainWindow", "+/-"))
        self.pushButton_17.setText(_translate("MainWindow", "/"))
        self.pushButton_6.setText(_translate("MainWindow", "5"))
        self.pushButton.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "2"))
        self.pushButton_16.setText(_translate("MainWindow", "Limpa"))
        self.pushButton_11.setText(_translate("MainWindow", "-"))
        self.pushButton_18.setText(_translate("MainWindow", "%"))
        self.pushButton_12.setText(_translate("MainWindow", "+"))
        self.pushButton_13.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
